services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: challenge-mindfactory-backend
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: challenge-mindfactory-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    restart: unless-stopped
